from typing import Optional, List
from pydantic import BaseModel, Field, field_validator
from langchain_text_splitters import MarkdownHeaderTextSplitter, RecursiveCharacterTextSplitter
from langchain_ollama import ChatOllama

# 1. The Schema with Validators and Optional Fields
class FinancialMetrics(BaseModel):
    company_name: Optional[str] = Field(default=None, description="The full name of the company.")
    fiscal_year: Optional[int] = Field(default=None, description="The 4-digit fiscal year of the report.")
    total_revenue: Optional[float] = Field(default=None, description="Total revenue or sales.")
    net_income: Optional[float] = Field(default=None, description="Net income or net profit.")
    key_risks: Optional[List[str]] = Field(default_factory=list, description="Top risk factors mentioned.")

    # Automatically normalize large numbers down to millions
    @field_validator('total_revenue', 'net_income')
    @classmethod
    def normalize_to_millions(cls, v: Optional[float]) -> Optional[float]:
        if v is not None and v > 1000000: 
            return v / 1000000.0
        return v

def process_document(markdown_file_path: str):
    print(f"Loading document: {markdown_file_path}")
    
    # 2. Read the Markdown file generated by Docling
    try:
        with open(markdown_file_path, 'r', encoding='utf-8') as f:
            markdown_text = f.read()
    except FileNotFoundError:
        print(f"Error: Could not find {markdown_file_path}. Please make sure you ran the Phase 1 script.")
        return

    # 3. Define the Markdown headers we want to split on
    headers_to_split_on = [
        ("#", "Header 1"),
        ("##", "Header 2"),
        ("###", "Header 3"),
    ]

    # 4. Perform the Header Split
    markdown_splitter = MarkdownHeaderTextSplitter(headers_to_split_on=headers_to_split_on)
    header_chunks = markdown_splitter.split_text(markdown_text)

    # 5. Apply a character splitter as a safety net for massive sections
    chunk_size = 4000
    chunk_overlap = 200
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size, chunk_overlap=chunk_overlap
    )
    final_chunks = text_splitter.split_documents(header_chunks)

    print(f"Document logically split into {len(final_chunks)} chunks based on Markdown headers.")

    # 6. Initialize the local LLM
    print("Initializing local Gemma 4 model...")
    llm = ChatOllama(model="gemma4:e2b", temperature=0.0)
    structured_llm = llm.with_structured_output(FinancialMetrics)

    # 7. Process the chunks
    extracted_data = []
    
    print("\n--- Beginning Extraction Sequence ---")
    
    # Limiting to the first 10 chunks for testing purposes
    for i, chunk in enumerate(final_chunks[:10]):
        # Get the section name from metadata, default to "Intro" if none exists
        section_name = chunk.metadata.get('Header 2', chunk.metadata.get('Header 1', 'Uncategorized Section'))
        print(f"\nScanning Chunk {i+1} | Section: '{section_name}'...")
        
        try:
            # Invoke the model on the chunk
            result = structured_llm.invoke(chunk.page_content)
            
            # Check if the LLM actually found anything useful in this chunk
            if result.total_revenue or result.net_income or result.key_risks:
                extracted_data.append(result)
                print(f"  -> Found Data! Revenue: {result.total_revenue} | Net Income: {result.net_income}")
                if result.key_risks:
                    print(f"  -> Found {len(result.key_risks)} Risk Factors")
            else:
                print("  -> No targeted financial metrics found in this chunk.")
                
        except Exception as e:
            print(f"  -> Extraction failed on this chunk: {e}")

    print("\n--- Summary of Extracted Objects ---")
    for data in extracted_data:
        print(data.model_dump(exclude_none=True))

if __name__ == "__main__":
    # Ensure this points to the actual markdown file you generated
    # You can create a dummy file named 'parsed_10k.md' to test it if needed.
    process_document("dmart_anuala_report.md")